/**
 * FrankenSpec
 * Bandwidth's Frankensteined API Spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BandwidthMessage from './BandwidthMessage';

/**
 * The BandwidthCallbackMessage model module.
 * @module model/BandwidthCallbackMessage
 * @version 1.0.0
 */
class BandwidthCallbackMessage {
    /**
     * Constructs a new <code>BandwidthCallbackMessage</code>.
     * @alias module:model/BandwidthCallbackMessage
     */
    constructor() { 
        
        BandwidthCallbackMessage.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BandwidthCallbackMessage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BandwidthCallbackMessage} obj Optional instance to populate.
     * @return {module:model/BandwidthCallbackMessage} The populated <code>BandwidthCallbackMessage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BandwidthCallbackMessage();

            if (data.hasOwnProperty('time')) {
                obj['time'] = ApiClient.convertToType(data['time'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('to')) {
                obj['to'] = ApiClient.convertToType(data['to'], 'String');
            }
            if (data.hasOwnProperty('errorCode')) {
                obj['errorCode'] = ApiClient.convertToType(data['errorCode'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = BandwidthMessage.constructFromObject(data['message']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} time
 */
BandwidthCallbackMessage.prototype['time'] = undefined;

/**
 * @member {String} type
 */
BandwidthCallbackMessage.prototype['type'] = undefined;

/**
 * @member {String} to
 */
BandwidthCallbackMessage.prototype['to'] = undefined;

/**
 * @member {String} errorCode
 */
BandwidthCallbackMessage.prototype['errorCode'] = undefined;

/**
 * @member {String} description
 */
BandwidthCallbackMessage.prototype['description'] = undefined;

/**
 * @member {module:model/BandwidthMessage} message
 */
BandwidthCallbackMessage.prototype['message'] = undefined;






export default BandwidthCallbackMessage;

