/**
 * FrankenSpec
 * Bandwidth's Frankensteined API Spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BandwidthMessageItem model module.
 * @module model/BandwidthMessageItem
 * @version 1.0.0
 */
class BandwidthMessageItem {
    /**
     * Constructs a new <code>BandwidthMessageItem</code>.
     * @alias module:model/BandwidthMessageItem
     */
    constructor() { 
        
        BandwidthMessageItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BandwidthMessageItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BandwidthMessageItem} obj Optional instance to populate.
     * @return {module:model/BandwidthMessageItem} The populated <code>BandwidthMessageItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BandwidthMessageItem();

            if (data.hasOwnProperty('messageId')) {
                obj['messageId'] = ApiClient.convertToType(data['messageId'], 'String');
            }
            if (data.hasOwnProperty('accountId')) {
                obj['accountId'] = ApiClient.convertToType(data['accountId'], 'String');
            }
            if (data.hasOwnProperty('sourceTn')) {
                obj['sourceTn'] = ApiClient.convertToType(data['sourceTn'], 'String');
            }
            if (data.hasOwnProperty('destinationTn')) {
                obj['destinationTn'] = ApiClient.convertToType(data['destinationTn'], 'String');
            }
            if (data.hasOwnProperty('messageStatus')) {
                obj['messageStatus'] = ApiClient.convertToType(data['messageStatus'], 'String');
            }
            if (data.hasOwnProperty('messageDirection')) {
                obj['messageDirection'] = ApiClient.convertToType(data['messageDirection'], 'String');
            }
            if (data.hasOwnProperty('messageType')) {
                obj['messageType'] = ApiClient.convertToType(data['messageType'], 'String');
            }
            if (data.hasOwnProperty('segmentCount')) {
                obj['segmentCount'] = ApiClient.convertToType(data['segmentCount'], 'Number');
            }
            if (data.hasOwnProperty('errorCode')) {
                obj['errorCode'] = ApiClient.convertToType(data['errorCode'], 'Number');
            }
            if (data.hasOwnProperty('receiveTime')) {
                obj['receiveTime'] = ApiClient.convertToType(data['receiveTime'], 'String');
            }
            if (data.hasOwnProperty('carrierName')) {
                obj['carrierName'] = ApiClient.convertToType(data['carrierName'], 'String');
            }
            if (data.hasOwnProperty('messageSize')) {
                obj['messageSize'] = ApiClient.convertToType(data['messageSize'], 'Number');
            }
            if (data.hasOwnProperty('messageLength')) {
                obj['messageLength'] = ApiClient.convertToType(data['messageLength'], 'Number');
            }
            if (data.hasOwnProperty('attachmentCount')) {
                obj['attachmentCount'] = ApiClient.convertToType(data['attachmentCount'], 'Number');
            }
            if (data.hasOwnProperty('recipientCount')) {
                obj['recipientCount'] = ApiClient.convertToType(data['recipientCount'], 'Number');
            }
            if (data.hasOwnProperty('campaignClass')) {
                obj['campaignClass'] = ApiClient.convertToType(data['campaignClass'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The message id
 * @member {String} messageId
 */
BandwidthMessageItem.prototype['messageId'] = undefined;

/**
 * The account id of the message
 * @member {String} accountId
 */
BandwidthMessageItem.prototype['accountId'] = undefined;

/**
 * The source phone number of the message
 * @member {String} sourceTn
 */
BandwidthMessageItem.prototype['sourceTn'] = undefined;

/**
 * The recipient phone number of the message
 * @member {String} destinationTn
 */
BandwidthMessageItem.prototype['destinationTn'] = undefined;

/**
 * The status of the message
 * @member {String} messageStatus
 */
BandwidthMessageItem.prototype['messageStatus'] = undefined;

/**
 * The direction of the message relative to Bandwidth. INBOUND or OUTBOUND
 * @member {String} messageDirection
 */
BandwidthMessageItem.prototype['messageDirection'] = undefined;

/**
 * The type of message. sms or mms
 * @member {String} messageType
 */
BandwidthMessageItem.prototype['messageType'] = undefined;

/**
 * The number of segments the message was sent as
 * @member {Number} segmentCount
 */
BandwidthMessageItem.prototype['segmentCount'] = undefined;

/**
 * The numeric error code of the message
 * @member {Number} errorCode
 */
BandwidthMessageItem.prototype['errorCode'] = undefined;

/**
 * The ISO 8601 datetime of the message
 * @member {String} receiveTime
 */
BandwidthMessageItem.prototype['receiveTime'] = undefined;

/**
 * The name of the carrier. Not currently supported for MMS, coming soon
 * @member {String} carrierName
 */
BandwidthMessageItem.prototype['carrierName'] = undefined;

/**
 * The size of the message including message content and headers
 * @member {Number} messageSize
 */
BandwidthMessageItem.prototype['messageSize'] = undefined;

/**
 * The length of the message content
 * @member {Number} messageLength
 */
BandwidthMessageItem.prototype['messageLength'] = undefined;

/**
 * The number of attachments the message has
 * @member {Number} attachmentCount
 */
BandwidthMessageItem.prototype['attachmentCount'] = undefined;

/**
 * The number of recipients the message has
 * @member {Number} recipientCount
 */
BandwidthMessageItem.prototype['recipientCount'] = undefined;

/**
 * The campaign class of the message, if it has one
 * @member {String} campaignClass
 */
BandwidthMessageItem.prototype['campaignClass'] = undefined;






export default BandwidthMessageItem;

