/**
 * FrankenSpec
 * Bandwidth's Frankensteined API Spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ConferenceMemberState model module.
 * @module model/ConferenceMemberState
 * @version 1.0.0
 */
class ConferenceMemberState {
    /**
     * Constructs a new <code>ConferenceMemberState</code>.
     * @alias module:model/ConferenceMemberState
     */
    constructor() { 
        
        ConferenceMemberState.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ConferenceMemberState</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConferenceMemberState} obj Optional instance to populate.
     * @return {module:model/ConferenceMemberState} The populated <code>ConferenceMemberState</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConferenceMemberState();

            if (data.hasOwnProperty('callId')) {
                obj['callId'] = ApiClient.convertToType(data['callId'], 'String');
            }
            if (data.hasOwnProperty('conferenceId')) {
                obj['conferenceId'] = ApiClient.convertToType(data['conferenceId'], 'String');
            }
            if (data.hasOwnProperty('memberUrl')) {
                obj['memberUrl'] = ApiClient.convertToType(data['memberUrl'], 'String');
            }
            if (data.hasOwnProperty('mute')) {
                obj['mute'] = ApiClient.convertToType(data['mute'], 'Boolean');
            }
            if (data.hasOwnProperty('hold')) {
                obj['hold'] = ApiClient.convertToType(data['hold'], 'Boolean');
            }
            if (data.hasOwnProperty('callIdsToCoach')) {
                obj['callIdsToCoach'] = ApiClient.convertToType(data['callIdsToCoach'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} callId
 */
ConferenceMemberState.prototype['callId'] = undefined;

/**
 * @member {String} conferenceId
 */
ConferenceMemberState.prototype['conferenceId'] = undefined;

/**
 * @member {String} memberUrl
 */
ConferenceMemberState.prototype['memberUrl'] = undefined;

/**
 * @member {Boolean} mute
 */
ConferenceMemberState.prototype['mute'] = undefined;

/**
 * @member {Boolean} hold
 */
ConferenceMemberState.prototype['hold'] = undefined;

/**
 * @member {Array.<String>} callIdsToCoach
 */
ConferenceMemberState.prototype['callIdsToCoach'] = undefined;






export default ConferenceMemberState;

