/**
 * FrankenSpec
 * Bandwidth's Frankensteined API Spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Diversion model module.
 * @module model/Diversion
 * @version 1.0.0
 */
class Diversion {
    /**
     * Constructs a new <code>Diversion</code>.
     * @alias module:model/Diversion
     */
    constructor() { 
        
        Diversion.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Diversion</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Diversion} obj Optional instance to populate.
     * @return {module:model/Diversion} The populated <code>Diversion</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Diversion();

            if (data.hasOwnProperty('reason')) {
                obj['reason'] = ApiClient.convertToType(data['reason'], 'String');
            }
            if (data.hasOwnProperty('privacy')) {
                obj['privacy'] = ApiClient.convertToType(data['privacy'], 'String');
            }
            if (data.hasOwnProperty('unknown')) {
                obj['unknown'] = ApiClient.convertToType(data['unknown'], 'String');
            }
            if (data.hasOwnProperty('origTo')) {
                obj['origTo'] = ApiClient.convertToType(data['origTo'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} reason
 */
Diversion.prototype['reason'] = undefined;

/**
 * @member {String} privacy
 */
Diversion.prototype['privacy'] = undefined;

/**
 * @member {String} unknown
 */
Diversion.prototype['unknown'] = undefined;

/**
 * @member {String} origTo
 */
Diversion.prototype['origTo'] = undefined;






export default Diversion;

