/**
 * FrankenSpec
 * Bandwidth's Frankensteined API Spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ErrorWithRequest model module.
 * @module model/ErrorWithRequest
 * @version 1.0.0
 */
class ErrorWithRequest {
    /**
     * Constructs a new <code>ErrorWithRequest</code>.
     * @alias module:model/ErrorWithRequest
     */
    constructor() { 
        
        ErrorWithRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ErrorWithRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ErrorWithRequest} obj Optional instance to populate.
     * @return {module:model/ErrorWithRequest} The populated <code>ErrorWithRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ErrorWithRequest();

            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
            if (data.hasOwnProperty('requestId')) {
                obj['requestId'] = ApiClient.convertToType(data['requestId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * An error message pertaining to what the issue could be
 * @member {String} error
 */
ErrorWithRequest.prototype['error'] = undefined;

/**
 * The associated requestId from AWS
 * @member {String} requestId
 */
ErrorWithRequest.prototype['requestId'] = undefined;






export default ErrorWithRequest;

