/**
 * FrankenSpec
 * Bandwidth's Frankensteined API Spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ForbiddenRequest model module.
 * @module model/ForbiddenRequest
 * @version 1.0.0
 */
class ForbiddenRequest {
    /**
     * Constructs a new <code>ForbiddenRequest</code>.
     * @alias module:model/ForbiddenRequest
     */
    constructor() { 
        
        ForbiddenRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ForbiddenRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ForbiddenRequest} obj Optional instance to populate.
     * @return {module:model/ForbiddenRequest} The populated <code>ForbiddenRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ForbiddenRequest();

            if (data.hasOwnProperty('Message')) {
                obj['Message'] = ApiClient.convertToType(data['Message'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The message containing the reason behind the request being forbidden
 * @member {String} Message
 */
ForbiddenRequest.prototype['Message'] = undefined;






export default ForbiddenRequest;

