/**
 * FrankenSpec
 * Bandwidth's Frankensteined API Spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MessagingException model module.
 * @module model/MessagingException
 * @version 1.0.0
 */
class MessagingException {
    /**
     * Constructs a new <code>MessagingException</code>.
     * @alias module:model/MessagingException
     * @param type {String} 
     * @param description {String} 
     */
    constructor(type, description) { 
        
        MessagingException.initialize(this, type, description);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, description) { 
        obj['type'] = type;
        obj['description'] = description;
    }

    /**
     * Constructs a <code>MessagingException</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MessagingException} obj Optional instance to populate.
     * @return {module:model/MessagingException} The populated <code>MessagingException</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MessagingException();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} type
 */
MessagingException.prototype['type'] = undefined;

/**
 * @member {String} description
 */
MessagingException.prototype['description'] = undefined;






export default MessagingException;

