/**
 * FrankenSpec
 * Bandwidth's Frankensteined API Spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ModifyConferenceRequest model module.
 * @module model/ModifyConferenceRequest
 * @version 1.0.0
 */
class ModifyConferenceRequest {
    /**
     * Constructs a new <code>ModifyConferenceRequest</code>.
     * @alias module:model/ModifyConferenceRequest
     */
    constructor() { 
        
        ModifyConferenceRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ModifyConferenceRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModifyConferenceRequest} obj Optional instance to populate.
     * @return {module:model/ModifyConferenceRequest} The populated <code>ModifyConferenceRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModifyConferenceRequest();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('redirectUrl')) {
                obj['redirectUrl'] = ApiClient.convertToType(data['redirectUrl'], 'String');
            }
            if (data.hasOwnProperty('redirectFallbackUrl')) {
                obj['redirectFallbackUrl'] = ApiClient.convertToType(data['redirectFallbackUrl'], 'String');
            }
            if (data.hasOwnProperty('redirectMethod')) {
                obj['redirectMethod'] = ApiClient.convertToType(data['redirectMethod'], 'String');
            }
            if (data.hasOwnProperty('redirectFallbackMethod')) {
                obj['redirectFallbackMethod'] = ApiClient.convertToType(data['redirectFallbackMethod'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('fallbackUsername')) {
                obj['fallbackUsername'] = ApiClient.convertToType(data['fallbackUsername'], 'String');
            }
            if (data.hasOwnProperty('fallbackPassword')) {
                obj['fallbackPassword'] = ApiClient.convertToType(data['fallbackPassword'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ModifyConferenceRequest.StatusEnum} status
 */
ModifyConferenceRequest.prototype['status'] = undefined;

/**
 * @member {String} redirectUrl
 */
ModifyConferenceRequest.prototype['redirectUrl'] = undefined;

/**
 * @member {String} redirectFallbackUrl
 */
ModifyConferenceRequest.prototype['redirectFallbackUrl'] = undefined;

/**
 * @member {module:model/ModifyConferenceRequest.RedirectMethodEnum} redirectMethod
 */
ModifyConferenceRequest.prototype['redirectMethod'] = undefined;

/**
 * @member {module:model/ModifyConferenceRequest.RedirectFallbackMethodEnum} redirectFallbackMethod
 */
ModifyConferenceRequest.prototype['redirectFallbackMethod'] = undefined;

/**
 * @member {String} username
 */
ModifyConferenceRequest.prototype['username'] = undefined;

/**
 * @member {String} password
 */
ModifyConferenceRequest.prototype['password'] = undefined;

/**
 * @member {String} fallbackUsername
 */
ModifyConferenceRequest.prototype['fallbackUsername'] = undefined;

/**
 * @member {String} fallbackPassword
 */
ModifyConferenceRequest.prototype['fallbackPassword'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
ModifyConferenceRequest['StatusEnum'] = {

    /**
     * value: "active"
     * @const
     */
    "active": "active",

    /**
     * value: "completed"
     * @const
     */
    "completed": "completed"
};


/**
 * Allowed values for the <code>redirectMethod</code> property.
 * @enum {String}
 * @readonly
 */
ModifyConferenceRequest['RedirectMethodEnum'] = {

    /**
     * value: "POST"
     * @const
     */
    "POST": "POST",

    /**
     * value: "GET"
     * @const
     */
    "GET": "GET"
};


/**
 * Allowed values for the <code>redirectFallbackMethod</code> property.
 * @enum {String}
 * @readonly
 */
ModifyConferenceRequest['RedirectFallbackMethodEnum'] = {

    /**
     * value: "POST"
     * @const
     */
    "POST": "POST",

    /**
     * value: "GET"
     * @const
     */
    "GET": "GET"
};



export default ModifyConferenceRequest;

