/**
 * FrankenSpec
 * Bandwidth's Frankensteined API Spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OrderStatusResult model module.
 * @module model/OrderStatusResult
 * @version 1.0.0
 */
class OrderStatusResult {
    /**
     * Constructs a new <code>OrderStatusResult</code>.
     * @alias module:model/OrderStatusResult
     */
    constructor() { 
        
        OrderStatusResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OrderStatusResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OrderStatusResult} obj Optional instance to populate.
     * @return {module:model/OrderStatusResult} The populated <code>OrderStatusResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrderStatusResult();

            if (data.hasOwnProperty('Response Code')) {
                obj['Response Code'] = ApiClient.convertToType(data['Response Code'], 'Number');
            }
            if (data.hasOwnProperty('Message')) {
                obj['Message'] = ApiClient.convertToType(data['Message'], 'String');
            }
            if (data.hasOwnProperty('E.164 Format')) {
                obj['E.164 Format'] = ApiClient.convertToType(data['E.164 Format'], 'String');
            }
            if (data.hasOwnProperty('Formatted')) {
                obj['Formatted'] = ApiClient.convertToType(data['Formatted'], 'String');
            }
            if (data.hasOwnProperty('Country')) {
                obj['Country'] = ApiClient.convertToType(data['Country'], 'String');
            }
            if (data.hasOwnProperty('Line Type')) {
                obj['Line Type'] = ApiClient.convertToType(data['Line Type'], 'String');
            }
            if (data.hasOwnProperty('Line Provider')) {
                obj['Line Provider'] = ApiClient.convertToType(data['Line Provider'], 'String');
            }
            if (data.hasOwnProperty('Mobile Country Code')) {
                obj['Mobile Country Code'] = ApiClient.convertToType(data['Mobile Country Code'], 'String');
            }
            if (data.hasOwnProperty('Mobile Network Code')) {
                obj['Mobile Network Code'] = ApiClient.convertToType(data['Mobile Network Code'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Our vendor's response code.
 * @member {Number} Response Code
 */
OrderStatusResult.prototype['Response Code'] = undefined;

/**
 * Message associated with the response code.
 * @member {String} Message
 */
OrderStatusResult.prototype['Message'] = undefined;

/**
 * The telephone number in E.164 format.
 * @member {String} E.164 Format
 */
OrderStatusResult.prototype['E.164 Format'] = undefined;

/**
 * The formatted version of the telephone number.
 * @member {String} Formatted
 */
OrderStatusResult.prototype['Formatted'] = undefined;

/**
 * The country of the telephone number.
 * @member {String} Country
 */
OrderStatusResult.prototype['Country'] = undefined;

/**
 * The line type of the telephone number.
 * @member {String} Line Type
 */
OrderStatusResult.prototype['Line Type'] = undefined;

/**
 * The service provider of the telephone number.
 * @member {String} Line Provider
 */
OrderStatusResult.prototype['Line Provider'] = undefined;

/**
 * The first half of the Home Network Identity (HNI).
 * @member {String} Mobile Country Code
 */
OrderStatusResult.prototype['Mobile Country Code'] = undefined;

/**
 * The second half of the HNI.
 * @member {String} Mobile Network Code
 */
OrderStatusResult.prototype['Mobile Network Code'] = undefined;






export default OrderStatusResult;

