/**
 * FrankenSpec
 * Bandwidth's Frankensteined API Spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PageInfo model module.
 * @module model/PageInfo
 * @version 1.0.0
 */
class PageInfo {
    /**
     * Constructs a new <code>PageInfo</code>.
     * @alias module:model/PageInfo
     */
    constructor() { 
        
        PageInfo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PageInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PageInfo} obj Optional instance to populate.
     * @return {module:model/PageInfo} The populated <code>PageInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PageInfo();

            if (data.hasOwnProperty('prevPage')) {
                obj['prevPage'] = ApiClient.convertToType(data['prevPage'], 'String');
            }
            if (data.hasOwnProperty('nextPage')) {
                obj['nextPage'] = ApiClient.convertToType(data['nextPage'], 'String');
            }
            if (data.hasOwnProperty('prevPageToken')) {
                obj['prevPageToken'] = ApiClient.convertToType(data['prevPageToken'], 'String');
            }
            if (data.hasOwnProperty('nextPageToken')) {
                obj['nextPageToken'] = ApiClient.convertToType(data['nextPageToken'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The link to the previous page for pagination
 * @member {String} prevPage
 */
PageInfo.prototype['prevPage'] = undefined;

/**
 * The link to the next page for pagination
 * @member {String} nextPage
 */
PageInfo.prototype['nextPage'] = undefined;

/**
 * The isolated pagination token for the previous page
 * @member {String} prevPageToken
 */
PageInfo.prototype['prevPageToken'] = undefined;

/**
 * The isolated pagination token for the next page
 * @member {String} nextPageToken
 */
PageInfo.prototype['nextPageToken'] = undefined;






export default PageInfo;

