/**
 * FrankenSpec
 * Bandwidth's Frankensteined API Spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ParticipantSubscription model module.
 * @module model/ParticipantSubscription
 * @version 1.0.0
 */
class ParticipantSubscription {
    /**
     * Constructs a new <code>ParticipantSubscription</code>.
     * @alias module:model/ParticipantSubscription
     * @param participantId {String} Participant the subscriber should be subscribed to
     */
    constructor(participantId) { 
        
        ParticipantSubscription.initialize(this, participantId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, participantId) { 
        obj['participantId'] = participantId;
    }

    /**
     * Constructs a <code>ParticipantSubscription</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ParticipantSubscription} obj Optional instance to populate.
     * @return {module:model/ParticipantSubscription} The populated <code>ParticipantSubscription</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ParticipantSubscription();

            if (data.hasOwnProperty('participantId')) {
                obj['participantId'] = ApiClient.convertToType(data['participantId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Participant the subscriber should be subscribed to
 * @member {String} participantId
 */
ParticipantSubscription.prototype['participantId'] = undefined;






export default ParticipantSubscription;

