/**
 * FrankenSpec
 * Bandwidth's Frankensteined API Spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Subscriptions from './Subscriptions';

/**
 * The Participant model module.
 * @module model/Participant
 * @version 1.0.0
 */
class Participant {
    /**
     * Constructs a new <code>Participant</code>.
     * A participant object
     * @alias module:model/Participant
     */
    constructor() { 
        
        Participant.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Participant</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Participant} obj Optional instance to populate.
     * @return {module:model/Participant} The populated <code>Participant</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Participant();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('callbackUrl')) {
                obj['callbackUrl'] = ApiClient.convertToType(data['callbackUrl'], 'String');
            }
            if (data.hasOwnProperty('publishPermissions')) {
                obj['publishPermissions'] = ApiClient.convertToType(data['publishPermissions'], ['String']);
            }
            if (data.hasOwnProperty('sessions')) {
                obj['sessions'] = ApiClient.convertToType(data['sessions'], ['String']);
            }
            if (data.hasOwnProperty('subscriptions')) {
                obj['subscriptions'] = Subscriptions.constructFromObject(data['subscriptions']);
            }
            if (data.hasOwnProperty('tag')) {
                obj['tag'] = ApiClient.convertToType(data['tag'], 'String');
            }
            if (data.hasOwnProperty('deviceApiVersion')) {
                obj['deviceApiVersion'] = ApiClient.convertToType(data['deviceApiVersion'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Unique id of the participant
 * @member {String} id
 */
Participant.prototype['id'] = undefined;

/**
 * Full callback url to use for notifications about this participant
 * @member {String} callbackUrl
 */
Participant.prototype['callbackUrl'] = undefined;

/**
 * Defines if this participant can publish audio or video
 * @member {Array.<module:model/Participant.PublishPermissionsEnum>} publishPermissions
 */
Participant.prototype['publishPermissions'] = undefined;

/**
 * List of session ids this participant is associated with  Capped to one 
 * @member {Array.<String>} sessions
 */
Participant.prototype['sessions'] = undefined;

/**
 * @member {module:model/Subscriptions} subscriptions
 */
Participant.prototype['subscriptions'] = undefined;

/**
 * User defined tag to associate with the participant
 * @member {String} tag
 */
Participant.prototype['tag'] = undefined;

/**
 * Optional field to define the device api version of this participant
 * @member {module:model/Participant.DeviceApiVersionEnum} deviceApiVersion
 * @default 'V2'
 */
Participant.prototype['deviceApiVersion'] = 'V2';





/**
 * Allowed values for the <code>publishPermissions</code> property.
 * @enum {String}
 * @readonly
 */
Participant['PublishPermissionsEnum'] = {

    /**
     * value: "AUDIO"
     * @const
     */
    "AUDIO": "AUDIO",

    /**
     * value: "VIDEO"
     * @const
     */
    "VIDEO": "VIDEO"
};


/**
 * Allowed values for the <code>deviceApiVersion</code> property.
 * @enum {String}
 * @readonly
 */
Participant['DeviceApiVersionEnum'] = {

    /**
     * value: "V3"
     * @const
     */
    "V3": "V3",

    /**
     * value: "V2"
     * @const
     */
    "V2": "V2"
};



export default Participant;

