/**
 * FrankenSpec
 * Bandwidth's Frankensteined API Spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TranscribeRecordingRequest model module.
 * @module model/TranscribeRecordingRequest
 * @version 1.0.0
 */
class TranscribeRecordingRequest {
    /**
     * Constructs a new <code>TranscribeRecordingRequest</code>.
     * @alias module:model/TranscribeRecordingRequest
     */
    constructor() { 
        
        TranscribeRecordingRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TranscribeRecordingRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TranscribeRecordingRequest} obj Optional instance to populate.
     * @return {module:model/TranscribeRecordingRequest} The populated <code>TranscribeRecordingRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TranscribeRecordingRequest();

            if (data.hasOwnProperty('callbackUrl')) {
                obj['callbackUrl'] = ApiClient.convertToType(data['callbackUrl'], 'String');
            }
            if (data.hasOwnProperty('callbackMethod')) {
                obj['callbackMethod'] = ApiClient.convertToType(data['callbackMethod'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('tag')) {
                obj['tag'] = ApiClient.convertToType(data['tag'], 'String');
            }
            if (data.hasOwnProperty('callbackTimeout')) {
                obj['callbackTimeout'] = ApiClient.convertToType(data['callbackTimeout'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} callbackUrl
 */
TranscribeRecordingRequest.prototype['callbackUrl'] = undefined;

/**
 * @member {module:model/TranscribeRecordingRequest.CallbackMethodEnum} callbackMethod
 */
TranscribeRecordingRequest.prototype['callbackMethod'] = undefined;

/**
 * @member {String} username
 */
TranscribeRecordingRequest.prototype['username'] = undefined;

/**
 * @member {String} password
 */
TranscribeRecordingRequest.prototype['password'] = undefined;

/**
 * @member {String} tag
 */
TranscribeRecordingRequest.prototype['tag'] = undefined;

/**
 * @member {Number} callbackTimeout
 */
TranscribeRecordingRequest.prototype['callbackTimeout'] = undefined;





/**
 * Allowed values for the <code>callbackMethod</code> property.
 * @enum {String}
 * @readonly
 */
TranscribeRecordingRequest['CallbackMethodEnum'] = {

    /**
     * value: "POST"
     * @const
     */
    "POST": "POST",

    /**
     * value: "GET"
     * @const
     */
    "GET": "GET"
};



export default TranscribeRecordingRequest;

