/**
 * FrankenSpec
 * Bandwidth's Frankensteined API Spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TranscriptionMetadata model module.
 * @module model/TranscriptionMetadata
 * @version 1.0.0
 */
class TranscriptionMetadata {
    /**
     * Constructs a new <code>TranscriptionMetadata</code>.
     * @alias module:model/TranscriptionMetadata
     */
    constructor() { 
        
        TranscriptionMetadata.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TranscriptionMetadata</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TranscriptionMetadata} obj Optional instance to populate.
     * @return {module:model/TranscriptionMetadata} The populated <code>TranscriptionMetadata</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TranscriptionMetadata();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('completedTime')) {
                obj['completedTime'] = ApiClient.convertToType(data['completedTime'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
TranscriptionMetadata.prototype['id'] = undefined;

/**
 * The current status of the transcription. Current values are 'none', 'processing', 'available', 'error', 'timeout', 'file-size-too-big', and 'file-size-too-small'. Additional states may be added in the future, so your application must be tolerant of unknown values.
 * @member {String} status
 */
TranscriptionMetadata.prototype['status'] = undefined;

/**
 * @member {String} completedTime
 */
TranscriptionMetadata.prototype['completedTime'] = undefined;

/**
 * @member {String} url
 */
TranscriptionMetadata.prototype['url'] = undefined;






export default TranscriptionMetadata;

