/**
 * FrankenSpec
 * Bandwidth's Frankensteined API Spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TwoFactorVoiceResponse model module.
 * @module model/TwoFactorVoiceResponse
 * @version 1.0.0
 */
class TwoFactorVoiceResponse {
    /**
     * Constructs a new <code>TwoFactorVoiceResponse</code>.
     * @alias module:model/TwoFactorVoiceResponse
     */
    constructor() { 
        
        TwoFactorVoiceResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TwoFactorVoiceResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TwoFactorVoiceResponse} obj Optional instance to populate.
     * @return {module:model/TwoFactorVoiceResponse} The populated <code>TwoFactorVoiceResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TwoFactorVoiceResponse();

            if (data.hasOwnProperty('callId')) {
                obj['callId'] = ApiClient.convertToType(data['callId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} callId
 */
TwoFactorVoiceResponse.prototype['callId'] = undefined;






export default TwoFactorVoiceResponse;

