/**
 * FrankenSpec
 * Bandwidth's Frankensteined API Spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TwoFactorMessagingResponse model module.
 * @module model/TwoFactorMessagingResponse
 * @version 1.0.0
 */
class TwoFactorMessagingResponse {
    /**
     * Constructs a new <code>TwoFactorMessagingResponse</code>.
     * @alias module:model/TwoFactorMessagingResponse
     */
    constructor() { 
        
        TwoFactorMessagingResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TwoFactorMessagingResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TwoFactorMessagingResponse} obj Optional instance to populate.
     * @return {module:model/TwoFactorMessagingResponse} The populated <code>TwoFactorMessagingResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TwoFactorMessagingResponse();

            if (data.hasOwnProperty('messageId')) {
                obj['messageId'] = ApiClient.convertToType(data['messageId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} messageId
 */
TwoFactorMessagingResponse.prototype['messageId'] = undefined;






export default TwoFactorMessagingResponse;

