/**
 * FrankenSpec
 * Bandwidth's Frankensteined API Spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TwoFactorCodeRequestSchema model module.
 * @module model/TwoFactorCodeRequestSchema
 * @version 1.0.0
 */
class TwoFactorCodeRequestSchema {
    /**
     * Constructs a new <code>TwoFactorCodeRequestSchema</code>.
     * @alias module:model/TwoFactorCodeRequestSchema
     * @param to {String} The phone number to send the 2fa code to.
     * @param from {String} The application phone number, the sender of the 2fa code.
     * @param applicationId {String} The application unique ID, obtained from Bandwidth.
     * @param message {String} The message format of the 2fa code.  There are three values that the system will replace \"{CODE}\", \"{NAME}\", \"{SCOPE}\".  The \"{SCOPE}\" and \"{NAME} value template are optional, while \"{CODE}\" must be supplied.  As the name would suggest, code will be replace with the actual 2fa code.  Name is replaced with the application name, configured during provisioning of 2fa.  The scope value is the same value sent during the call and partitioned by the server.
     * @param digits {Number} The number of digits for your 2fa code.  The valid number ranges from 2 to 8, inclusively.
     */
    constructor(to, from, applicationId, message, digits) { 
        
        TwoFactorCodeRequestSchema.initialize(this, to, from, applicationId, message, digits);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, to, from, applicationId, message, digits) { 
        obj['to'] = to;
        obj['from'] = from;
        obj['applicationId'] = applicationId;
        obj['message'] = message;
        obj['digits'] = digits;
    }

    /**
     * Constructs a <code>TwoFactorCodeRequestSchema</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TwoFactorCodeRequestSchema} obj Optional instance to populate.
     * @return {module:model/TwoFactorCodeRequestSchema} The populated <code>TwoFactorCodeRequestSchema</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TwoFactorCodeRequestSchema();

            if (data.hasOwnProperty('to')) {
                obj['to'] = ApiClient.convertToType(data['to'], 'String');
            }
            if (data.hasOwnProperty('from')) {
                obj['from'] = ApiClient.convertToType(data['from'], 'String');
            }
            if (data.hasOwnProperty('applicationId')) {
                obj['applicationId'] = ApiClient.convertToType(data['applicationId'], 'String');
            }
            if (data.hasOwnProperty('scope')) {
                obj['scope'] = ApiClient.convertToType(data['scope'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('digits')) {
                obj['digits'] = ApiClient.convertToType(data['digits'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * The phone number to send the 2fa code to.
 * @member {String} to
 */
TwoFactorCodeRequestSchema.prototype['to'] = undefined;

/**
 * The application phone number, the sender of the 2fa code.
 * @member {String} from
 */
TwoFactorCodeRequestSchema.prototype['from'] = undefined;

/**
 * The application unique ID, obtained from Bandwidth.
 * @member {String} applicationId
 */
TwoFactorCodeRequestSchema.prototype['applicationId'] = undefined;

/**
 * An optional field to denote what scope or action the 2fa code is addressing.  If not supplied, defaults to \"2FA\".
 * @member {String} scope
 */
TwoFactorCodeRequestSchema.prototype['scope'] = undefined;

/**
 * The message format of the 2fa code.  There are three values that the system will replace \"{CODE}\", \"{NAME}\", \"{SCOPE}\".  The \"{SCOPE}\" and \"{NAME} value template are optional, while \"{CODE}\" must be supplied.  As the name would suggest, code will be replace with the actual 2fa code.  Name is replaced with the application name, configured during provisioning of 2fa.  The scope value is the same value sent during the call and partitioned by the server.
 * @member {String} message
 */
TwoFactorCodeRequestSchema.prototype['message'] = undefined;

/**
 * The number of digits for your 2fa code.  The valid number ranges from 2 to 8, inclusively.
 * @member {Number} digits
 */
TwoFactorCodeRequestSchema.prototype['digits'] = undefined;






export default TwoFactorCodeRequestSchema;

