/**
 * FrankenSpec
 * Bandwidth's Frankensteined API Spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TwoFactorVerifyCodeResponse model module.
 * @module model/TwoFactorVerifyCodeResponse
 * @version 1.0.0
 */
class TwoFactorVerifyCodeResponse {
    /**
     * Constructs a new <code>TwoFactorVerifyCodeResponse</code>.
     * @alias module:model/TwoFactorVerifyCodeResponse
     */
    constructor() { 
        
        TwoFactorVerifyCodeResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TwoFactorVerifyCodeResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TwoFactorVerifyCodeResponse} obj Optional instance to populate.
     * @return {module:model/TwoFactorVerifyCodeResponse} The populated <code>TwoFactorVerifyCodeResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TwoFactorVerifyCodeResponse();

            if (data.hasOwnProperty('valid')) {
                obj['valid'] = ApiClient.convertToType(data['valid'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} valid
 */
TwoFactorVerifyCodeResponse.prototype['valid'] = undefined;






export default TwoFactorVerifyCodeResponse;

