/**
 * FrankenSpec
 * Bandwidth's Frankensteined API Spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UnauthorizedRequest model module.
 * @module model/UnauthorizedRequest
 * @version 1.0.0
 */
class UnauthorizedRequest {
    /**
     * Constructs a new <code>UnauthorizedRequest</code>.
     * @alias module:model/UnauthorizedRequest
     */
    constructor() { 
        
        UnauthorizedRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UnauthorizedRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UnauthorizedRequest} obj Optional instance to populate.
     * @return {module:model/UnauthorizedRequest} The populated <code>UnauthorizedRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UnauthorizedRequest();

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The message containing the reason behind the request being unauthorized
 * @member {String} message
 */
UnauthorizedRequest.prototype['message'] = undefined;






export default UnauthorizedRequest;

