/**
 * FrankenSpec
 * Bandwidth's Frankensteined API Spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NodeSdk);
  }
}(this, function(expect, NodeSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NodeSdk.CreateCallRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CreateCallRequest', function() {
    it('should create an instance of CreateCallRequest', function() {
      // uncomment below and update the code to test CreateCallRequest
      //var instane = new NodeSdk.CreateCallRequest();
      //expect(instance).to.be.a(NodeSdk.CreateCallRequest);
    });

    it('should have the property from (base name: "from")', function() {
      // uncomment below and update the code to test the property from
      //var instance = new NodeSdk.CreateCallRequest();
      //expect(instance).to.be();
    });

    it('should have the property to (base name: "to")', function() {
      // uncomment below and update the code to test the property to
      //var instance = new NodeSdk.CreateCallRequest();
      //expect(instance).to.be();
    });

    it('should have the property uui (base name: "uui")', function() {
      // uncomment below and update the code to test the property uui
      //var instance = new NodeSdk.CreateCallRequest();
      //expect(instance).to.be();
    });

    it('should have the property callTimeout (base name: "callTimeout")', function() {
      // uncomment below and update the code to test the property callTimeout
      //var instance = new NodeSdk.CreateCallRequest();
      //expect(instance).to.be();
    });

    it('should have the property callbackTimeout (base name: "callbackTimeout")', function() {
      // uncomment below and update the code to test the property callbackTimeout
      //var instance = new NodeSdk.CreateCallRequest();
      //expect(instance).to.be();
    });

    it('should have the property answerUrl (base name: "answerUrl")', function() {
      // uncomment below and update the code to test the property answerUrl
      //var instance = new NodeSdk.CreateCallRequest();
      //expect(instance).to.be();
    });

    it('should have the property answerFallbackUrl (base name: "answerFallbackUrl")', function() {
      // uncomment below and update the code to test the property answerFallbackUrl
      //var instance = new NodeSdk.CreateCallRequest();
      //expect(instance).to.be();
    });

    it('should have the property username (base name: "username")', function() {
      // uncomment below and update the code to test the property username
      //var instance = new NodeSdk.CreateCallRequest();
      //expect(instance).to.be();
    });

    it('should have the property password (base name: "password")', function() {
      // uncomment below and update the code to test the property password
      //var instance = new NodeSdk.CreateCallRequest();
      //expect(instance).to.be();
    });

    it('should have the property fallbackUsername (base name: "fallbackUsername")', function() {
      // uncomment below and update the code to test the property fallbackUsername
      //var instance = new NodeSdk.CreateCallRequest();
      //expect(instance).to.be();
    });

    it('should have the property fallbackPassword (base name: "fallbackPassword")', function() {
      // uncomment below and update the code to test the property fallbackPassword
      //var instance = new NodeSdk.CreateCallRequest();
      //expect(instance).to.be();
    });

    it('should have the property answerMethod (base name: "answerMethod")', function() {
      // uncomment below and update the code to test the property answerMethod
      //var instance = new NodeSdk.CreateCallRequest();
      //expect(instance).to.be();
    });

    it('should have the property answerFallbackMethod (base name: "answerFallbackMethod")', function() {
      // uncomment below and update the code to test the property answerFallbackMethod
      //var instance = new NodeSdk.CreateCallRequest();
      //expect(instance).to.be();
    });

    it('should have the property disconnectUrl (base name: "disconnectUrl")', function() {
      // uncomment below and update the code to test the property disconnectUrl
      //var instance = new NodeSdk.CreateCallRequest();
      //expect(instance).to.be();
    });

    it('should have the property disconnectMethod (base name: "disconnectMethod")', function() {
      // uncomment below and update the code to test the property disconnectMethod
      //var instance = new NodeSdk.CreateCallRequest();
      //expect(instance).to.be();
    });

    it('should have the property tag (base name: "tag")', function() {
      // uncomment below and update the code to test the property tag
      //var instance = new NodeSdk.CreateCallRequest();
      //expect(instance).to.be();
    });

    it('should have the property applicationId (base name: "applicationId")', function() {
      // uncomment below and update the code to test the property applicationId
      //var instance = new NodeSdk.CreateCallRequest();
      //expect(instance).to.be();
    });

    it('should have the property machineDetection (base name: "machineDetection")', function() {
      // uncomment below and update the code to test the property machineDetection
      //var instance = new NodeSdk.CreateCallRequest();
      //expect(instance).to.be();
    });

  });

}));
