/**
 * FrankenSpec
 * Bandwidth's Frankensteined API Spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NodeSdk);
  }
}(this, function(expect, NodeSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NodeSdk.Diversion();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Diversion', function() {
    it('should create an instance of Diversion', function() {
      // uncomment below and update the code to test Diversion
      //var instane = new NodeSdk.Diversion();
      //expect(instance).to.be.a(NodeSdk.Diversion);
    });

    it('should have the property reason (base name: "reason")', function() {
      // uncomment below and update the code to test the property reason
      //var instance = new NodeSdk.Diversion();
      //expect(instance).to.be();
    });

    it('should have the property privacy (base name: "privacy")', function() {
      // uncomment below and update the code to test the property privacy
      //var instance = new NodeSdk.Diversion();
      //expect(instance).to.be();
    });

    it('should have the property unknown (base name: "unknown")', function() {
      // uncomment below and update the code to test the property unknown
      //var instance = new NodeSdk.Diversion();
      //expect(instance).to.be();
    });

    it('should have the property origTo (base name: "origTo")', function() {
      // uncomment below and update the code to test the property origTo
      //var instance = new NodeSdk.Diversion();
      //expect(instance).to.be();
    });

  });

}));
