/**
 * FrankenSpec
 * Bandwidth's Frankensteined API Spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NodeSdk);
  }
}(this, function(expect, NodeSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NodeSdk.MachineDetectionConfiguration();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MachineDetectionConfiguration', function() {
    it('should create an instance of MachineDetectionConfiguration', function() {
      // uncomment below and update the code to test MachineDetectionConfiguration
      //var instane = new NodeSdk.MachineDetectionConfiguration();
      //expect(instance).to.be.a(NodeSdk.MachineDetectionConfiguration);
    });

    it('should have the property mode (base name: "mode")', function() {
      // uncomment below and update the code to test the property mode
      //var instance = new NodeSdk.MachineDetectionConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property detectionTimeout (base name: "detectionTimeout")', function() {
      // uncomment below and update the code to test the property detectionTimeout
      //var instance = new NodeSdk.MachineDetectionConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property silenceTimeout (base name: "silenceTimeout")', function() {
      // uncomment below and update the code to test the property silenceTimeout
      //var instance = new NodeSdk.MachineDetectionConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property speechThreshold (base name: "speechThreshold")', function() {
      // uncomment below and update the code to test the property speechThreshold
      //var instance = new NodeSdk.MachineDetectionConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property speechEndThreshold (base name: "speechEndThreshold")', function() {
      // uncomment below and update the code to test the property speechEndThreshold
      //var instance = new NodeSdk.MachineDetectionConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property delayResult (base name: "delayResult")', function() {
      // uncomment below and update the code to test the property delayResult
      //var instance = new NodeSdk.MachineDetectionConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property callbackUrl (base name: "callbackUrl")', function() {
      // uncomment below and update the code to test the property callbackUrl
      //var instance = new NodeSdk.MachineDetectionConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property callbackMethod (base name: "callbackMethod")', function() {
      // uncomment below and update the code to test the property callbackMethod
      //var instance = new NodeSdk.MachineDetectionConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property fallbackUrl (base name: "fallbackUrl")', function() {
      // uncomment below and update the code to test the property fallbackUrl
      //var instance = new NodeSdk.MachineDetectionConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property fallbackMethod (base name: "fallbackMethod")', function() {
      // uncomment below and update the code to test the property fallbackMethod
      //var instance = new NodeSdk.MachineDetectionConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property username (base name: "username")', function() {
      // uncomment below and update the code to test the property username
      //var instance = new NodeSdk.MachineDetectionConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property password (base name: "password")', function() {
      // uncomment below and update the code to test the property password
      //var instance = new NodeSdk.MachineDetectionConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property fallbackUsername (base name: "fallbackUsername")', function() {
      // uncomment below and update the code to test the property fallbackUsername
      //var instance = new NodeSdk.MachineDetectionConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property fallbackPassword (base name: "fallbackPassword")', function() {
      // uncomment below and update the code to test the property fallbackPassword
      //var instance = new NodeSdk.MachineDetectionConfiguration();
      //expect(instance).to.be();
    });

  });

}));
