/**
 * FrankenSpec
 * Bandwidth's Frankensteined API Spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NodeSdk);
  }
}(this, function(expect, NodeSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NodeSdk.ModifyCallRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ModifyCallRequest', function() {
    it('should create an instance of ModifyCallRequest', function() {
      // uncomment below and update the code to test ModifyCallRequest
      //var instane = new NodeSdk.ModifyCallRequest();
      //expect(instance).to.be.a(NodeSdk.ModifyCallRequest);
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instance = new NodeSdk.ModifyCallRequest();
      //expect(instance).to.be();
    });

    it('should have the property redirectUrl (base name: "redirectUrl")', function() {
      // uncomment below and update the code to test the property redirectUrl
      //var instance = new NodeSdk.ModifyCallRequest();
      //expect(instance).to.be();
    });

    it('should have the property redirectFallbackUrl (base name: "redirectFallbackUrl")', function() {
      // uncomment below and update the code to test the property redirectFallbackUrl
      //var instance = new NodeSdk.ModifyCallRequest();
      //expect(instance).to.be();
    });

    it('should have the property redirectMethod (base name: "redirectMethod")', function() {
      // uncomment below and update the code to test the property redirectMethod
      //var instance = new NodeSdk.ModifyCallRequest();
      //expect(instance).to.be();
    });

    it('should have the property redirectFallbackMethod (base name: "redirectFallbackMethod")', function() {
      // uncomment below and update the code to test the property redirectFallbackMethod
      //var instance = new NodeSdk.ModifyCallRequest();
      //expect(instance).to.be();
    });

    it('should have the property username (base name: "username")', function() {
      // uncomment below and update the code to test the property username
      //var instance = new NodeSdk.ModifyCallRequest();
      //expect(instance).to.be();
    });

    it('should have the property password (base name: "password")', function() {
      // uncomment below and update the code to test the property password
      //var instance = new NodeSdk.ModifyCallRequest();
      //expect(instance).to.be();
    });

    it('should have the property fallbackUsername (base name: "fallbackUsername")', function() {
      // uncomment below and update the code to test the property fallbackUsername
      //var instance = new NodeSdk.ModifyCallRequest();
      //expect(instance).to.be();
    });

    it('should have the property fallbackPassword (base name: "fallbackPassword")', function() {
      // uncomment below and update the code to test the property fallbackPassword
      //var instance = new NodeSdk.ModifyCallRequest();
      //expect(instance).to.be();
    });

    it('should have the property tag (base name: "tag")', function() {
      // uncomment below and update the code to test the property tag
      //var instance = new NodeSdk.ModifyCallRequest();
      //expect(instance).to.be();
    });

  });

}));
