/**
 * FrankenSpec
 * Bandwidth's Frankensteined API Spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NodeSdk);
  }
}(this, function(expect, NodeSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NodeSdk.OrderStatusResult();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OrderStatusResult', function() {
    it('should create an instance of OrderStatusResult', function() {
      // uncomment below and update the code to test OrderStatusResult
      //var instane = new NodeSdk.OrderStatusResult();
      //expect(instance).to.be.a(NodeSdk.OrderStatusResult);
    });

    it('should have the property responseCode (base name: "Response Code")', function() {
      // uncomment below and update the code to test the property responseCode
      //var instance = new NodeSdk.OrderStatusResult();
      //expect(instance).to.be();
    });

    it('should have the property message (base name: "Message")', function() {
      // uncomment below and update the code to test the property message
      //var instance = new NodeSdk.OrderStatusResult();
      //expect(instance).to.be();
    });

    it('should have the property e164Format (base name: "E.164 Format")', function() {
      // uncomment below and update the code to test the property e164Format
      //var instance = new NodeSdk.OrderStatusResult();
      //expect(instance).to.be();
    });

    it('should have the property formatted (base name: "Formatted")', function() {
      // uncomment below and update the code to test the property formatted
      //var instance = new NodeSdk.OrderStatusResult();
      //expect(instance).to.be();
    });

    it('should have the property country (base name: "Country")', function() {
      // uncomment below and update the code to test the property country
      //var instance = new NodeSdk.OrderStatusResult();
      //expect(instance).to.be();
    });

    it('should have the property lineType (base name: "Line Type")', function() {
      // uncomment below and update the code to test the property lineType
      //var instance = new NodeSdk.OrderStatusResult();
      //expect(instance).to.be();
    });

    it('should have the property lineProvider (base name: "Line Provider")', function() {
      // uncomment below and update the code to test the property lineProvider
      //var instance = new NodeSdk.OrderStatusResult();
      //expect(instance).to.be();
    });

    it('should have the property mobileCountryCode (base name: "Mobile Country Code")', function() {
      // uncomment below and update the code to test the property mobileCountryCode
      //var instance = new NodeSdk.OrderStatusResult();
      //expect(instance).to.be();
    });

    it('should have the property mobileNetworkCode (base name: "Mobile Network Code")', function() {
      // uncomment below and update the code to test the property mobileNetworkCode
      //var instance = new NodeSdk.OrderStatusResult();
      //expect(instance).to.be();
    });

  });

}));
