/**
 * FrankenSpec
 * Bandwidth's Frankensteined API Spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NodeSdk);
  }
}(this, function(expect, NodeSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NodeSdk.SessionsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SessionsApi', function() {
    describe('addParticipantToSession', function() {
      it('should call addParticipantToSession successfully', function(done) {
        //uncomment below and update the code to test addParticipantToSession
        //instance.addParticipantToSession(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createSession', function() {
      it('should call createSession successfully', function(done) {
        //uncomment below and update the code to test createSession
        //instance.createSession(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteSession', function() {
      it('should call deleteSession successfully', function(done) {
        //uncomment below and update the code to test deleteSession
        //instance.deleteSession(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getParticipantSubscriptions', function() {
      it('should call getParticipantSubscriptions successfully', function(done) {
        //uncomment below and update the code to test getParticipantSubscriptions
        //instance.getParticipantSubscriptions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSession', function() {
      it('should call getSession successfully', function(done) {
        //uncomment below and update the code to test getSession
        //instance.getSession(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listSessionParticipants', function() {
      it('should call listSessionParticipants successfully', function(done) {
        //uncomment below and update the code to test listSessionParticipants
        //instance.listSessionParticipants(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('removeParticipantFromSession', function() {
      it('should call removeParticipantFromSession successfully', function(done) {
        //uncomment below and update the code to test removeParticipantFromSession
        //instance.removeParticipantFromSession(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateParticipantSubscriptions', function() {
      it('should call updateParticipantSubscriptions successfully', function(done) {
        //uncomment below and update the code to test updateParticipantSubscriptions
        //instance.updateParticipantSubscriptions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
